Repository yonghan8650/ProjectHRD, pull requests merged in 2024-03, with the labels that each got.

#7 Feat 테스트
  ProjectHRD/.classpath
  ProjectHRD/.settings/org.eclipse.jdt.core.prefs
  ProjectHRD/.settings/org.eclipse.wst.common.component
  ProjectHRD/src/main/java/com/bswill/controller/BoardController.java
  ProjectHRD/src/main/java/com/bswill/domain/BoardCri.java
  ProjectHRD/src/main/java/com/bswill/domain/BoardVO.java
  ProjectHRD/src/main/java/com/bswill/domain/PageMakerDTO.java
  ProjectHRD/src/main/java/com/bswill/persistence/BoardDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/BoardDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/BoardService.java
  ProjectHRD/src/main/java/com/bswill/service/BoardServiceImpl.java
  ProjectHRD/src/main/resources/log4j.xml
  ProjectHRD/src/main/resources/log4jdbc.log4j2.properties
  ProjectHRD/src/main/resources/logback.xml
  ProjectHRD/src/main/resources/mappers/boardMapper.xml
  ProjectHRD/src/main/resources/mybatis-config.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/root-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/security-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/board/list.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/modify.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/read.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/register.jsp
  ProjectHRD/src/main/webapp/WEB-INF/web.xml
  ProjectHRD/src/test/resources/log4j.xml
  ProjectHRD/target/classes/com/bswill/controller/BoardController.class
  ProjectHRD/target/classes/com/bswill/domain/BoardCri.class
  ProjectHRD/target/classes/com/bswill/domain/BoardVO.class
  ProjectHRD/target/classes/com/bswill/domain/PageMakerDTO.class
  ProjectHRD/target/classes/com/bswill/persistence/BoardDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/BoardDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/BoardService.class
  ProjectHRD/target/classes/com/bswill/service/BoardServiceImpl.class
  ProjectHRD/target/classes/log4j.xml
  ProjectHRD/target/classes/log4jdbc.log4j2.properties
  ProjectHRD/target/classes/logback.xml
  ProjectHRD/target/classes/mappers/boardMapper.xml
  ProjectHRD/target/classes/mybatis-config.xml
  ProjectHRD/target/m2e-wtp/web-resources/META-INF/maven/com.bswill/controller/pom.properties
  ProjectHRD/target/test-classes/log4j.xml
Labels: Add Function

#26 family Eevet 1차 완료
  ProjectHRD/src/main/java/com/bswill/controller/EmpController.java
  ProjectHRD/src/main/java/com/bswill/controller/EmployeeController.java
  ProjectHRD/src/main/java/com/bswill/domain/EmployeeVO.java
  ProjectHRD/src/main/java/com/bswill/domain/EventVO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EventDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EventDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/EventService.java
  ProjectHRD/src/main/java/com/bswill/service/EventServiceImpl.java
  ProjectHRD/src/main/resources/mappers/employeeMapper.xml
  ProjectHRD/src/main/resources/mappers/eventMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/applyEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/listEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/viewEmpAccountInfo.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/viewEvent.jsp
  ProjectHRD/target/classes/com/bswill/controller/EmpController.class
  ProjectHRD/target/classes/com/bswill/controller/EmployeeController.class
  ProjectHRD/target/classes/com/bswill/controller/SalaryController.class
  ProjectHRD/target/classes/com/bswill/domain/EmployeeVO.class
  ProjectHRD/target/classes/com/bswill/domain/EventVO.class
  ProjectHRD/target/classes/com/bswill/domain/NotificationVO.class
  ProjectHRD/target/classes/com/bswill/persistence/EventDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/EventDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/SalaryDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/SalaryDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/EmployeeServiceImpl.class
  ProjectHRD/target/classes/com/bswill/service/EventService.class
  ProjectHRD/target/classes/com/bswill/service/EventServiceImpl.class
  ProjectHRD/target/classes/com/bswill/service/SalaryService.class
  ProjectHRD/target/classes/com/bswill/service/SalaryServiceImpl.class
  ProjectHRD/target/classes/mappers/employeeMapper.xml
  ProjectHRD/target/classes/mappers/eventMapper.xml
Labels: Add Function

#28 Feat 비밀번호 변경
  ProjectHRD/src/main/java/com/bswill/controller/BoardController.java
  ProjectHRD/src/main/java/com/bswill/controller/CommonController.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/security/CustomLoginFailureHandler.java
  ProjectHRD/src/main/java/com/bswill/service/CommonService.java
  ProjectHRD/src/main/java/com/bswill/service/CommonServiceImpl.java
  ProjectHRD/src/main/resources/mappers/commonMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/security-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/board/list.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/modify.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/read.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/changePw.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/customLogin.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/main.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/test/java/com/bswill/controller/MemberTest.java
  ProjectHRD/target/classes/com/bswill/controller/BoardController.class
  ProjectHRD/target/classes/com/bswill/controller/CommonController.class
  ProjectHRD/target/classes/com/bswill/persistence/CommonDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/CommonDAOImpl.class
  ProjectHRD/target/classes/com/bswill/security/CustomLoginFailureHandler.class
  ProjectHRD/target/classes/com/bswill/service/CommonService.class
  ProjectHRD/target/classes/com/bswill/service/CommonServiceImpl.class
  ProjectHRD/target/classes/mappers/commonMapper.xml
  ProjectHRD/target/test-classes/com/bswill/controller/MemberTest.class
Labels: Add Function

#32 출퇴근 목록 검색, 페이징X
  ProjectHRD/src/main/java/com/bswill/controller/AttendanceController.java
  ProjectHRD/src/main/java/com/bswill/domain/AttendanceVO.java
  ProjectHRD/src/main/java/com/bswill/domain/SearchCriteria.java
  ProjectHRD/src/main/java/com/bswill/persistence/AttendanceDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/AttendanceDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/AttendanceService.java
  ProjectHRD/src/main/java/com/bswill/service/AttendanceServiceImpl.java
  ProjectHRD/src/main/resources/mappers/attendanceMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/attendance/list.jsp
  ProjectHRD/target/classes/com/bswill/controller/AttendanceController.class
  ProjectHRD/target/classes/com/bswill/domain/AttendanceVO.class
  ProjectHRD/target/classes/com/bswill/domain/SearchCriteria.class
  ProjectHRD/target/classes/com/bswill/persistence/AttendanceDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/AttendanceDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/AttendanceService.class
  ProjectHRD/target/classes/com/bswill/service/AttendanceServiceImpl.class
  ProjectHRD/target/classes/mappers/attendanceMapper.xml
Labels: Add Function

#36 Modifying board&common 뷰페이지, header.jsp, footer.jsp 수정 완료
  ProjectHRD/src/main/java/com/bswill/controller/CommonController.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/CommonService.java
  ProjectHRD/src/main/java/com/bswill/service/CommonServiceImpl.java
  ProjectHRD/src/main/resources/mappers/commonMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/board/list.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/modify.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/read.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/register.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/customLogin.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/customLogout.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/main.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/target/classes/com/bswill/controller/CommonController.class
  ProjectHRD/target/classes/com/bswill/persistence/CommonDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/CommonDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/CommonService.class
  ProjectHRD/target/classes/com/bswill/service/CommonServiceImpl.class
  ProjectHRD/target/classes/mappers/commonMapper.xml
Labels: Add Function

#37 update registEmp + notification
  ProjectHRD/src/main/java/com/bswill/controller/EmployeeController.java
  ProjectHRD/src/main/java/com/bswill/domain/AppointmentListVO.java
  ProjectHRD/src/main/java/com/bswill/domain/AppointmentVO.java
  ProjectHRD/src/main/java/com/bswill/domain/EmployeeVO.java
  ProjectHRD/src/main/java/com/bswill/domain/LicenseListVO.java
  ProjectHRD/src/main/java/com/bswill/domain/LicenseVO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeService.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeServiceImpl.java
  ProjectHRD/src/main/resources/mappers/employeeMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/security-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/applyEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/listEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/registEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/web.xml
  ProjectHRD/src/main/webapp/resources/js/registEmp.js
  ProjectHRD/src/test/java/com/bswill/controller/RegistTest.java
  ProjectHRD/target/classes/com/bswill/controller/EmployeeController.class
  ProjectHRD/target/classes/com/bswill/domain/AppointmentListVO.class
  ProjectHRD/target/classes/com/bswill/domain/AppointmentVO.class
  ProjectHRD/target/classes/com/bswill/domain/EmployeeVO.class
  ProjectHRD/target/classes/com/bswill/domain/LicenseListVO.class
  ProjectHRD/target/classes/com/bswill/domain/LicenseVO.class
  ProjectHRD/target/classes/com/bswill/persistence/EmployeeDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/EmployeeDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/EmployeeService.class
  ProjectHRD/target/classes/com/bswill/service/EmployeeServiceImpl.class
  ProjectHRD/target/classes/mappers/employeeMapper.xml
  ProjectHRD/target/test-classes/com/bswill/controller/RegistTest.class
Labels: Update Function

#40 update userinfo(user)
  ProjectHRD/src/main/java/com/bswill/controller/EmployeeController.java
  ProjectHRD/src/main/java/com/bswill/persistence/AppointmentDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/AppointmentDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/LicenseDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/LicenseDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/AppointmentService.java
  ProjectHRD/src/main/java/com/bswill/service/AppointmentServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeService.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/LicenseService.java
  ProjectHRD/src/main/java/com/bswill/service/LicenseServiceImpl.java
  ProjectHRD/src/main/resources/mappers/appointmentMapper.xml
  ProjectHRD/src/main/resources/mappers/employeeMapper.xml
  ProjectHRD/src/main/resources/mappers/licenseMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/viewEmp.jsp
  ProjectHRD/target/classes/com/bswill/controller/EmployeeController.class
  ProjectHRD/target/classes/com/bswill/controller/SalaryController.class
  ProjectHRD/target/classes/com/bswill/persistence/AppointmentDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/AppointmentDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/EmployeeDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/EmployeeDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/LicenseDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/LicenseDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/SalaryDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/SalaryDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/AppointmentService.class
  ProjectHRD/target/classes/com/bswill/service/AppointmentServiceImpl.class
  ProjectHRD/target/classes/com/bswill/service/EmployeeService.class
  ProjectHRD/target/classes/com/bswill/service/EmployeeServiceImpl.class
  ProjectHRD/target/classes/com/bswill/service/LicenseService.class
  ProjectHRD/target/classes/com/bswill/service/LicenseServiceImpl.class
  ProjectHRD/target/classes/com/bswill/service/SalaryService.class
  ProjectHRD/target/classes/com/bswill/service/SalaryServiceImpl.class
  ProjectHRD/target/classes/mappers/appointmentMapper.xml
  ProjectHRD/target/classes/mappers/employeeMapper.xml
  ProjectHRD/target/classes/mappers/licenseMapper.xml
Labels: Update Function

#44 휴가 신청 목록, 검색, 승인/반려
  ProjectHRD/src/main/java/com/bswill/controller/LeavesController.java
  ProjectHRD/src/main/java/com/bswill/domain/LeaveVO.java
  ProjectHRD/src/main/java/com/bswill/domain/ReqLeavesVO.java
  ProjectHRD/src/main/java/com/bswill/domain/Req_leavesVO.java
  ProjectHRD/src/main/java/com/bswill/persistence/LeavesDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/LeavesDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/LeavesService.java
  ProjectHRD/src/main/java/com/bswill/service/LeavesServiceImpl.java
  ProjectHRD/src/main/resources/mappers/leavesMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/leaves/requests.jsp
  ProjectHRD/target/classes/com/bswill/controller/LeavesController.class
  ProjectHRD/target/classes/com/bswill/domain/LeaveVO.class
  ProjectHRD/target/classes/com/bswill/domain/ReqLeavesVO.class
  ProjectHRD/target/classes/com/bswill/domain/Req_leavesVO.class
  ProjectHRD/target/classes/com/bswill/persistence/LeavesDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/LeavesDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/LeavesService.class
  ProjectHRD/target/classes/com/bswill/service/LeavesServiceImpl.class
  ProjectHRD/target/classes/mappers/leavesMapper.xml
Labels: Add Function

#47 board - modify, read 오류 수정 완료
  ProjectHRD/src/main/java/com/bswill/controller/BoardController.java
  ProjectHRD/src/main/resources/mappers/boardMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/board/modify.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/board/read.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/target/classes/com/bswill/controller/BoardController.class
  ProjectHRD/target/classes/mappers/boardMapper.xml
  ProjectHRD/target/classes/mybatis-config.xml
  ProjectHRD/target/m2e-wtp/web-resources/META-INF/maven/com.bswill/controller/pom.properties
Labels: bug

#50 header 알림, 조직도ui추가
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
Labels: Add Function

#51 Feat update administration emp
  ProjectHRD/src/main/java/com/bswill/controller/CommonController.java
  ProjectHRD/src/main/java/com/bswill/controller/EmployeeController.java
  ProjectHRD/src/main/java/com/bswill/persistence/AppointmentDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/AppointmentDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/LicenseDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/LicenseDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/AppointmentService.java
  ProjectHRD/src/main/java/com/bswill/service/AppointmentServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeService.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/LicenseService.java
  ProjectHRD/src/main/java/com/bswill/service/LicenseServiceImpl.java
  ProjectHRD/src/main/resources/mappers/appointmentMapper.xml
  ProjectHRD/src/main/resources/mappers/employeeMapper.xml
  ProjectHRD/src/main/resources/mappers/licenseMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/security-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/applyEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/listEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/listEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/modifyEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/registEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/viewEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/viewEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/main/webapp/WEB-INF/web.xml
  ProjectHRD/src/test/java/com/bswill/controller/ListEmpTest.java
  ProjectHRD/target/classes/com/bswill/controller/CommonController.class
  ProjectHRD/target/classes/com/bswill/controller/EmployeeController.class
  ProjectHRD/target/classes/com/bswill/persistence/AppointmentDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/AppointmentDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/EmployeeDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/EmployeeDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/LicenseDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/LicenseDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/AppointmentService.class
  ProjectHRD/target/classes/com/bswill/service/AppointmentServiceImpl.class
  ProjectHRD/target/classes/com/bswill/service/EmployeeService.class
  ProjectHRD/target/classes/com/bswill/service/EmployeeServiceImpl.class
  ProjectHRD/target/classes/com/bswill/service/LicenseService.class
  ProjectHRD/target/classes/com/bswill/service/LicenseServiceImpl.class
  ProjectHRD/target/classes/mappers/appointmentMapper.xml
  ProjectHRD/target/classes/mappers/employeeMapper.xml
  ProjectHRD/target/classes/mappers/licenseMapper.xml
  ProjectHRD/target/test-classes/com/bswill/controller/ListEmpTest.class
Labels: Update Function

#53 header.jsp 수정, CommonMapper수정
  ProjectHRD/src/main/resources/mappers/commonMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/target/classes/mappers/commonMapper.xml
Labels: Add Function

#55 메인 페이지 내용 추가 + 로고 사진 + common내용 추가
  ProjectHRD/src/main/java/com/bswill/controller/CommonController.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/CommonService.java
  ProjectHRD/src/main/java/com/bswill/service/CommonServiceImpl.java
  ProjectHRD/src/main/resources/mappers/commonMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/common/main.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/modifyEmp.jsp
  ProjectHRD/src/main/webapp/resources/img/bswill.jpg
  ProjectHRD/target/classes/com/bswill/controller/CommonController.class
  ProjectHRD/target/classes/com/bswill/persistence/CommonDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/CommonDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/CommonService.class
  ProjectHRD/target/classes/com/bswill/service/CommonServiceImpl.class
  ProjectHRD/target/classes/mappers/commonMapper.xml
Labels: Add Function

#56 Feat notification and organization
  ProjectHRD/src/main/java/com/bswill/controller/NotificationController.java
  ProjectHRD/src/main/java/com/bswill/controller/OrganizationChartController.java
  ProjectHRD/src/main/java/com/bswill/domain/OrganizationChartVO.java
  ProjectHRD/src/main/java/com/bswill/persistence/OrganizationChartDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/OrganizationChartDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/OrganizationChartService.java
  ProjectHRD/src/main/java/com/bswill/service/OrganizationChartServiceImpl.java
  ProjectHRD/src/main/resources/mappers/NotificationMapper.xml
  ProjectHRD/src/main/resources/mappers/OrganizationChartMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/noti/notifications.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/employeesByDept.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgDept.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgFavor.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgList.jsp
  ProjectHRD/target/classes/com/bswill/controller/NotificationController.class
  ProjectHRD/target/classes/com/bswill/controller/OrganizationChartController.class
  ProjectHRD/target/classes/com/bswill/domain/OrganizationChartVO.class
  ProjectHRD/target/classes/com/bswill/persistence/OrganizationChartDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/OrganizationChartDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/OrganizationChartService.class
  ProjectHRD/target/classes/com/bswill/service/OrganizationChartServiceImpl.class
  ProjectHRD/target/classes/mappers/NotificationMapper.xml
  ProjectHRD/target/classes/mappers/OrganizationChartMapper.xml
Labels: Add Function

#60 메인페이지 완료
  ProjectHRD/src/main/java/com/bswill/controller/CommonController.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/CommonService.java
  ProjectHRD/src/main/java/com/bswill/service/CommonServiceImpl.java
  ProjectHRD/src/main/resources/mappers/commonMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/common/main.jsp
  ProjectHRD/src/main/webapp/resources/img/orgchart.png
  ProjectHRD/target/classes/com/bswill/controller/CommonController.class
  ProjectHRD/target/classes/com/bswill/persistence/CommonDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/CommonDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/CommonService.class
  ProjectHRD/target/classes/com/bswill/service/CommonServiceImpl.class
  ProjectHRD/target/classes/mappers/commonMapper.xml
Labels: Add Function

#63 연차관리
  ProjectHRD/src/main/java/com/bswill/controller/AttendanceController.java
  ProjectHRD/src/main/java/com/bswill/controller/LeavesController.java
  ProjectHRD/src/main/java/com/bswill/domain/LeaveVO.java
  ProjectHRD/src/main/java/com/bswill/persistence/LeavesDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/LeavesDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/LeavesService.java
  ProjectHRD/src/main/java/com/bswill/service/LeavesServiceImpl.java
  ProjectHRD/src/main/resources/mappers/leavesMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/attendance/list.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/leaves/annualLeave.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/leaves/annualLeaveAdd.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/leaves/requests.jsp
Labels: Add Function

#67 common view 수정, url 접근권한 수정, 공지등록알림 추가
  ProjectHRD/src/main/java/com/bswill/controller/BoardController.java
  ProjectHRD/src/main/java/com/bswill/controller/CommonController.java
  ProjectHRD/src/main/java/com/bswill/persistence/BoardDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/BoardDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/BoardService.java
  ProjectHRD/src/main/java/com/bswill/service/BoardServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/CommonService.java
  ProjectHRD/src/main/java/com/bswill/service/CommonServiceImpl.java
  ProjectHRD/src/main/resources/mappers/boardMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/security-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/common/accessErr.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/changePw.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/customLogin.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/customLogout.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/main/webapp/resources/img/favicon.ico
Labels: Add Function

#69 Feat notification and organization
  ProjectHRD/src/main/java/com/bswill/controller/NotificationController.java
  ProjectHRD/src/main/java/com/bswill/controller/OrganizationChartController.java
  ProjectHRD/src/main/java/com/bswill/persistence/OrganizationChartDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/OrganizationChartDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/OrganizationChartService.java
  ProjectHRD/src/main/java/com/bswill/service/OrganizationChartServiceImpl.java
  ProjectHRD/src/main/resources/mappers/NotificationMapper.xml
  ProjectHRD/src/main/resources/mappers/OrganizationChartMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/noti/notifications.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgFavor.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgList.jsp
  ProjectHRD/target/classes/com/bswill/controller/NotificationController.class
  ProjectHRD/target/classes/com/bswill/controller/OrganizationChartController.class
  ProjectHRD/target/classes/com/bswill/persistence/OrganizationChartDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/OrganizationChartDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/OrganizationChartService.class
  ProjectHRD/target/classes/com/bswill/service/OrganizationChartServiceImpl.class
  ProjectHRD/target/classes/mappers/NotificationMapper.xml
  ProjectHRD/target/classes/mappers/OrganizationChartMapper.xml
Labels: Add Function

#70 date 입력 변경, submit 시 알람 추가
  ProjectHRD/src/main/java/com/bswill/controller/EmployeeController.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeService.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeServiceImpl.java
  ProjectHRD/src/main/resources/mappers/employeeMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/applyEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/modifyEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/registEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/viewEmp.jsp
Labels: Update Function

#76 조직도 대 수정.
  ProjectHRD/src/main/java/com/bswill/controller/OrganizationChartController.java
  ProjectHRD/src/main/java/com/bswill/persistence/OrganizationChartDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/OrganizationChartDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/OrganizationChartService.java
  ProjectHRD/src/main/java/com/bswill/service/OrganizationChartServiceImpl.java
  ProjectHRD/src/main/resources/mappers/OrganizationChartMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/security-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/employeesByDept.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgFavor.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgList.jsp
Labels: Add Function, Update Function

#77 Feat : 급여 페이지 권한 설정
  ProjectHRD/src/main/java/com/bswill/controller/SalaryController.java
  ProjectHRD/src/main/java/com/bswill/domain/SalaryCri.java
  ProjectHRD/src/main/java/com/bswill/persistence/SalaryDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/SalaryDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/SalaryService.java
  ProjectHRD/src/main/java/com/bswill/service/SalaryServiceImpl.java
  ProjectHRD/src/main/resources/mappers/SalaryMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/security-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salaryEnter.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salaryInfo.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salarySearch.jsp
Labels: Add Function, Update Function

#82 add auth_member
  ProjectHRD/src/main/java/com/bswill/controller/EmployeeController.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/security/CustomNoopPasswordEncoder.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeService.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeServiceImpl.java
  ProjectHRD/src/main/resources/mappers/employeeMapper.xml
Labels: Add Function, Update Function

#84 master merge
  ProjectHRD/src/main/java/com/bswill/controller/BoardController.java
  ProjectHRD/src/main/java/com/bswill/controller/CommonController.java
  ProjectHRD/src/main/java/com/bswill/controller/EmployeeController.java
  ProjectHRD/src/main/java/com/bswill/controller/NotificationController.java
  ProjectHRD/src/main/java/com/bswill/controller/OrganizationChartController.java
  ProjectHRD/src/main/java/com/bswill/controller/SalaryController.java
  ProjectHRD/src/main/java/com/bswill/domain/SalaryCri.java
  ProjectHRD/src/main/java/com/bswill/persistence/BoardDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/BoardDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/CommonDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/EmployeeDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/OrganizationChartDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/OrganizationChartDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/SalaryDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/SalaryDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/security/CustomNoopPasswordEncoder.java
  ProjectHRD/src/main/java/com/bswill/service/BoardService.java
  ProjectHRD/src/main/java/com/bswill/service/BoardServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/CommonService.java
  ProjectHRD/src/main/java/com/bswill/service/CommonServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeService.java
  ProjectHRD/src/main/java/com/bswill/service/EmployeeServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/OrganizationChartService.java
  ProjectHRD/src/main/java/com/bswill/service/OrganizationChartServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/SalaryService.java
  ProjectHRD/src/main/java/com/bswill/service/SalaryServiceImpl.java
  ProjectHRD/src/main/resources/mappers/NotificationMapper.xml
  ProjectHRD/src/main/resources/mappers/OrganizationChartMapper.xml
  ProjectHRD/src/main/resources/mappers/SalaryMapper.xml
  ProjectHRD/src/main/resources/mappers/boardMapper.xml
  ProjectHRD/src/main/resources/mappers/employeeMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/spring/security-context.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/common/accessErr.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/changePw.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/customLogin.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/common/customLogout.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/applyEvent.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/modifyEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/registEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/emp/viewEmp.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/noti/notifications.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/employeesByDept.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgFavor.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/org/orgList.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salaryEnter.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salaryInfo.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salarySearch.jsp
  ProjectHRD/src/main/webapp/resources/img/favicon.ico
  ProjectHRD/target/classes/com/bswill/controller/NotificationController.class
  ProjectHRD/target/classes/com/bswill/controller/OrganizationChartController.class
  ProjectHRD/target/classes/com/bswill/domain/NotificationVO.class
  ProjectHRD/target/classes/com/bswill/persistence/OrganizationChartDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/OrganizationChartDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/OrganizationChartService.class
  ProjectHRD/target/classes/com/bswill/service/OrganizationChartServiceImpl.class
  ProjectHRD/target/classes/mappers/NotificationMapper.xml
  ProjectHRD/target/classes/mappers/OrganizationChartMapper.xml
Labels: master merge

#88 검색 수정
  ProjectHRD/src/main/java/com/bswill/controller/AttendanceController.java
  ProjectHRD/src/main/java/com/bswill/controller/LeavesController.java
  ProjectHRD/src/main/java/com/bswill/domain/AttendanceVO.java
  ProjectHRD/src/main/java/com/bswill/persistence/AttendanceDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/AttendanceDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/LeavesDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/LeavesDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/LeavesService.java
  ProjectHRD/src/main/java/com/bswill/service/LeavesServiceImpl.java
  ProjectHRD/src/main/resources/mappers/attendanceMapper.xml
  ProjectHRD/src/main/resources/mappers/leavesMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/attendance/list.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/leaves/annualLeaveAdd.jsp
  ProjectHRD/target/classes/com/bswill/controller/AttendanceController.class
  ProjectHRD/target/classes/com/bswill/controller/LeavesController.class
  ProjectHRD/target/classes/com/bswill/domain/AttendanceVO.class
  ProjectHRD/target/classes/com/bswill/domain/LeaveVO.class
  ProjectHRD/target/classes/com/bswill/persistence/AttendanceDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/LeavesDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/LeavesDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/LeavesService.class
  ProjectHRD/target/classes/com/bswill/service/LeavesServiceImpl.class
  ProjectHRD/target/classes/mappers/attendanceMapper.xml
  ProjectHRD/target/classes/mappers/leavesMapper.xml
Labels: Add Function

#89 Fix email
  ProjectHRD/src/main/java/com/bswill/controller/MailController.java
  ProjectHRD/src/main/java/com/bswill/controller/SalaryController.java
  ProjectHRD/src/main/java/com/bswill/domain/SalaryCriteria.java
  ProjectHRD/src/main/java/com/bswill/persistence/SalaryDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/SalaryDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/SalaryService.java
  ProjectHRD/src/main/java/com/bswill/service/SalaryServiceImpl.java
  ProjectHRD/src/main/resources/mappers/SalaryMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salaryInfo.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salaryList.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salarySearch.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salarySearchMonthly.jsp
  ProjectHRD/target/classes/com/bswill/controller/MailController.class
  ProjectHRD/target/classes/com/bswill/controller/SalaryController.class
  ProjectHRD/target/classes/com/bswill/domain/SalaryCri.class
  ProjectHRD/target/classes/com/bswill/domain/SalaryCriteria.class
  ProjectHRD/target/classes/com/bswill/persistence/SalaryDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/SalaryDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/SalaryService.class
  ProjectHRD/target/classes/com/bswill/service/SalaryServiceImpl.class
  ProjectHRD/target/classes/mappers/SalaryMapper.xml
Labels: bug

#92 Fix : SalarySearch 버그 수정 완료
  ProjectHRD/src/main/resources/mappers/SalaryMapper.xml
  ProjectHRD/target/classes/mappers/SalaryMapper.xml
Labels: bug

#93 헤더 UI수정완료
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
Labels: UI

#95 master<-develop merge
  ProjectHRD/src/main/java/com/bswill/controller/AttendanceController.java
  ProjectHRD/src/main/java/com/bswill/controller/LeavesController.java
  ProjectHRD/src/main/java/com/bswill/controller/MailController.java
  ProjectHRD/src/main/java/com/bswill/controller/SalaryController.java
  ProjectHRD/src/main/java/com/bswill/domain/AttendanceVO.java
  ProjectHRD/src/main/java/com/bswill/domain/SalaryCriteria.java
  ProjectHRD/src/main/java/com/bswill/persistence/AttendanceDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/AttendanceDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/LeavesDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/LeavesDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/persistence/SalaryDAO.java
  ProjectHRD/src/main/java/com/bswill/persistence/SalaryDAOImpl.java
  ProjectHRD/src/main/java/com/bswill/service/LeavesService.java
  ProjectHRD/src/main/java/com/bswill/service/LeavesServiceImpl.java
  ProjectHRD/src/main/java/com/bswill/service/SalaryService.java
  ProjectHRD/src/main/java/com/bswill/service/SalaryServiceImpl.java
  ProjectHRD/src/main/resources/mappers/SalaryMapper.xml
  ProjectHRD/src/main/resources/mappers/attendanceMapper.xml
  ProjectHRD/src/main/resources/mappers/leavesMapper.xml
  ProjectHRD/src/main/webapp/WEB-INF/views/attendance/list.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/include/header.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/leaves/annualLeaveAdd.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salaryInfo.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salaryList.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salarySearch.jsp
  ProjectHRD/src/main/webapp/WEB-INF/views/salary/salarySearchMonthly.jsp
  ProjectHRD/target/classes/com/bswill/controller/AttendanceController.class
  ProjectHRD/target/classes/com/bswill/controller/LeavesController.class
  ProjectHRD/target/classes/com/bswill/controller/MailController.class
  ProjectHRD/target/classes/com/bswill/controller/SalaryController.class
  ProjectHRD/target/classes/com/bswill/domain/AttendanceVO.class
  ProjectHRD/target/classes/com/bswill/domain/LeaveVO.class
  ProjectHRD/target/classes/com/bswill/domain/SalaryCri.class
  ProjectHRD/target/classes/com/bswill/domain/SalaryCriteria.class
  ProjectHRD/target/classes/com/bswill/persistence/AttendanceDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/LeavesDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/LeavesDAOImpl.class
  ProjectHRD/target/classes/com/bswill/persistence/SalaryDAO.class
  ProjectHRD/target/classes/com/bswill/persistence/SalaryDAOImpl.class
  ProjectHRD/target/classes/com/bswill/service/LeavesService.class
  ProjectHRD/target/classes/com/bswill/service/LeavesServiceImpl.class
  ProjectHRD/target/classes/com/bswill/service/SalaryService.class
  ProjectHRD/target/classes/com/bswill/service/SalaryServiceImpl.class
  ProjectHRD/target/classes/mappers/SalaryMapper.xml
  ProjectHRD/target/classes/mappers/attendanceMapper.xml
  ProjectHRD/target/classes/mappers/leavesMapper.xml
Labels: master merge
